from tkinter import *
import tkinter
def home():
    home=tkinter.Tk()
    home.title("Chatting Program")
    home.geometry("400x300")
    home.iconbitmap('C:\code\WORKSPACE\PYTHON\SRC\채팅_프로그램\icon.ico')
    title=tkinter.Label(home, text="Chatting Program",font=("Arial",25))
    title.pack()
    image=tkinter.PhotoImage(file="C:\code\WORKSPACE\PYTHON\SRC\채팅_프로그램\messanger.png")
    logo=tkinter.Label(home,image=image)
    logo.pack()
    enter=tkinter.Label(text="[LOGIN]",pady=4)
    enter.pack()
    id_pw=tkinter.PanedWindow(relief="solid", bd=0.5)
    id_pw.pack()
    id_p=tkinter.Label(text="ID")
    id_pw.add(id_p)
    id_i=tkinter.Entry(width=18,insertwidth=1)
    id_pw.add(id_i)
    pw_pw=tkinter.PanedWindow(relief="solid",bd=0.5)
    pw_pw.pack()
    pw_p=tkinter.Label(text="🔑")
    pw_pw.add(pw_p)
    pw_i=tkinter.Entry(width=18,insertwidth=1,show="*")
    pw_pw.add(pw_i)
    empty=tkinter.PanedWindow()
    empty.pack()
    ent=tkinter.Label(text=" ")
    empty.add(ent)
    button=tkinter.PanedWindow()
    login=tkinter.Button(text="Login")
    button.add(login)
    join=tkinter.Button(text="Sign Up")
    button.add(join)
    button.pack()
    home.mainloop()
