import turtle
t=turtle.Turtle()
t.speed(30)
t.shape("turtle")
t.color("red")
t.left(90)
t.begin_fill()
t.circle(100,180)
t.circle(50,-180)
t.left(180)
t.circle(50,180)
t.end_fill()
t.color("blue")
t.begin_fill()
t.circle(100,-180)
t.circle(50,-180)
t.left(180)
t.circle(50,180)
t.end_fill()


def square(n):
    if n==1:
        t.begin_fill()
        for i in range(2):
            t.forward(20)
            t.left(90)
            t.forward(100)
            t.left(90)
        t.end_fill()
        t.penup()
    if n==2:
        t.begin_fill()
        for i in range(2):
            t.forward(20)
            t.left(90)
            t.forward(45)
            t.left(90)
        t.end_fill()
        t.penup()
        t.left(90)
        t.forward(55)
        t.right(90)
        t.pendown()
        t.begin_fill()
        for i in range(2):
            t.forward(20)
            t.left(90)
            t.forward(45)
            t.left(90)
        t.end_fill()
        t.penup()
        t.right(90)
        t.forward(55)
        t.left(90)

t.color("black")
t.right(30)
t.penup()
t.forward(100)
t.right(10)
t.pendown()
square(2)

t.forward(30)
t.pendown()
square(1)

t.forward(30)
t.pendown()
square(2)

t.setposition(-200,0)
t.right(140)
t.right(30)
t.penup()
t.forward(100)
t.right(10)
t.pendown()
square(1)
t.forward(30)
t.pendown()
square(2)
t.forward(30)
t.pendown()
square(1)

t.setposition(-200,0)
t.right(140)
t.left(30)
t.penup()
t.forward(100)
t.left(10)

t.right(90)
t.forward(100)
t.pendown()
t.left(90)

square(1)
t.forward(30)
t.pendown()
square(1)
t.forward(30)
t.pendown()
square(1)


t.setposition(0,0)
t.right(220)
t.left(30)
t.penup()
t.forward(100)
t.left(10)
t.right(90)
t.forward(100)
t.left(90)
square(2)
t.forward(30)
t.pendown()
square(2)
t.forward(30)
t.pendown()
square(2)

turtle.mainloop()
